language: node_js #设置语言

node_js: "12.13.0" #设置语言版本

cache:
  directories:
    - node_modules #缓存依赖

# S: Build Lifecycle
install:
  - npm i

script:
  - npm run test
  - npm run build

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - master